# Generated by Django 5.2.5 on 2025-08-13 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAPISpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("spec_content", models.JSONField()),
                ("version", models.CharField(default="3.0.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("operation_id", models.CharField(blank=True, max_length=200)),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("request_body", models.JSONField(default=dict)),
                ("responses", models.JSONField(default=dict)),
                ("tags", models.JSONField(default=list)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="api_specs.openapispec",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "method"],
                "unique_together": {("spec", "path", "method")},
            },
        ),
    ]
